# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack` gem.
# Please instead update this file by running `bin/tapioca gem rack`.


# Copyright (C) 2007-2019 Leah Neukirchen <http://leahneukirchen.org/infopage.html>
#
# Rack is freely distributable under the terms of an MIT-style license.
# See MIT-LICENSE or https://opensource.org/licenses/MIT.
#
# pkg:gem/rack#lib/rack/body_proxy.rb:3
module Rack; end

# Represents a 400 Bad Request error when input data fails to meet the
# requirements.
#
# pkg:gem/rack#lib/rack/bad_request.rb:6
module Rack::BadRequest; end

# Proxy for response bodies allowing calling a block when
# the response body is closed (after the response has been fully
# sent to the client).
#
# pkg:gem/rack#lib/rack/body_proxy.rb:7
class Rack::BodyProxy
  # Set the response body to wrap, and the block to call when the
  # response has been fully sent.
  #
  # pkg:gem/rack#lib/rack/body_proxy.rb:10
  def initialize(body, &block); end

  # If not already closed, close the wrapped body and
  # then call the block the proxy was initialized with.
  #
  # pkg:gem/rack#lib/rack/body_proxy.rb:28
  def close; end

  # Whether the proxy is closed.  The proxy starts as not closed,
  # and becomes closed on the first call to close.
  #
  # pkg:gem/rack#lib/rack/body_proxy.rb:40
  def closed?; end

  # Delegate missing methods to the wrapped body.
  #
  # pkg:gem/rack#lib/rack/body_proxy.rb:45
  def method_missing(method_name, *args, **_arg2, &block); end

  private

  # Return whether the wrapped body responds to the method.
  #
  # pkg:gem/rack#lib/rack/body_proxy.rb:17
  def respond_to_missing?(method_name, include_all = T.unsafe(nil)); end
end

# Response Header Keys
#
# pkg:gem/rack#lib/rack/constants.rb:19
Rack::CACHE_CONTROL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:35
Rack::CONNECT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:20
Rack::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:21
Rack::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:32
Rack::DELETE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:22
Rack::ETAG = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:23
Rack::EXPIRES = T.let(T.unsafe(nil), String)

# HTTP method verbs
#
# pkg:gem/rack#lib/rack/constants.rb:28
Rack::GET = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:33
Rack::HEAD = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:7
Rack::HTTPS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:16
Rack::HTTP_COOKIE = T.let(T.unsafe(nil), String)

# Request env keys
#
# pkg:gem/rack#lib/rack/constants.rb:5
Rack::HTTP_HOST = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:6
Rack::HTTP_PORT = T.let(T.unsafe(nil), String)

# Rack::Headers is a Hash subclass that downcases all keys.  It's designed
# to be used by rack applications that don't implement the Rack 3 SPEC
# (by using non-lowercase response header keys), automatically handling
# the downcasing of keys.
#
# pkg:gem/rack#lib/rack/headers.rb:8
class Rack::Headers < ::Hash
  # pkg:gem/rack#lib/rack/headers.rb:110
  def [](key); end

  # pkg:gem/rack#lib/rack/headers.rb:114
  def []=(key, value); end

  # pkg:gem/rack#lib/rack/headers.rb:119
  def assoc(key); end

  # pkg:gem/rack#lib/rack/headers.rb:123
  def compare_by_identity; end

  # pkg:gem/rack#lib/rack/headers.rb:127
  def delete(key); end

  # pkg:gem/rack#lib/rack/headers.rb:131
  def dig(key, *a); end

  # :nocov:
  #
  # pkg:gem/rack#lib/rack/headers.rb:227
  def except(*a); end

  # pkg:gem/rack#lib/rack/headers.rb:135
  def fetch(key, *default, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:140
  def fetch_values(*a); end

  # pkg:gem/rack#lib/rack/headers.rb:144
  def has_key?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:147
  def include?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:151
  def invert; end

  # pkg:gem/rack#lib/rack/headers.rb:148
  def key?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:149
  def member?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:157
  def merge(hash, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:196
  def merge!(hash, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:161
  def reject(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:167
  def replace(hash); end

  # pkg:gem/rack#lib/rack/headers.rb:172
  def select(&block); end

  # :nocov:
  #
  # pkg:gem/rack#lib/rack/headers.rb:205
  def slice(*a); end

  # pkg:gem/rack#lib/rack/headers.rb:117
  def store(key, value); end

  # pkg:gem/rack#lib/rack/headers.rb:178
  def to_proc; end

  # pkg:gem/rack#lib/rack/headers.rb:211
  def transform_keys(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:215
  def transform_keys!; end

  # pkg:gem/rack#lib/rack/headers.rb:182
  def transform_values(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:186
  def update(hash, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:198
  def values_at(*keys); end

  private

  # pkg:gem/rack#lib/rack/headers.rb:234
  def downcase_key(key); end

  class << self
    # pkg:gem/rack#lib/rack/headers.rb:91
    def [](*items); end
  end
end

# pkg:gem/rack#lib/rack/headers.rb:9
Rack::Headers::KNOWN_HEADERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/constants.rb:36
Rack::LINK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/mime.rb:4
module Rack::Mime
  private

  # Returns true if the given value is a mime match for the given mime match
  # specification, false otherwise.
  #
  #    Rack::Mime.match?('text/html', 'text/*') => true
  #    Rack::Mime.match?('text/plain', '*') => true
  #    Rack::Mime.match?('text/html', 'application/json') => false
  #
  # pkg:gem/rack#lib/rack/mime.rb:30
  def match?(value, matcher); end

  # Returns String with mime type if found, otherwise use +fallback+.
  # +ext+ should be filename extension in the '.ext' format that
  #       File.extname(file) returns.
  # +fallback+ may be any object
  #
  # Also see the documentation for MIME_TYPES
  #
  # Usage:
  #     Rack::Mime.mime_type('.foo')
  #
  # This is a shortcut for:
  #     Rack::Mime::MIME_TYPES.fetch('.foo', 'application/octet-stream')
  #
  # pkg:gem/rack#lib/rack/mime.rb:18
  def mime_type(ext, fallback = T.unsafe(nil)); end

  class << self
    # pkg:gem/rack#lib/rack/mime.rb:36
    def match?(value, matcher); end

    # pkg:gem/rack#lib/rack/mime.rb:21
    def mime_type(ext, fallback = T.unsafe(nil)); end
  end
end

# List of most common mime-types, selected various sources
# according to their usefulness in a webserving scope for Ruby
# users.
#
# To amend this list with your local mime.types list you can use:
#
#     require 'webrick/httputils'
#     list = WEBrick::HTTPUtils.load_mime_types('/etc/mime.types')
#     Rack::Mime::MIME_TYPES.merge!(list)
#
# N.B. On Ubuntu the mime.types file does not include the leading period, so
# users may need to modify the data before merging into the hash.
#
# pkg:gem/rack#lib/rack/mime.rb:51
Rack::Mime::MIME_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/constants.rb:34
Rack::OPTIONS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:31
Rack::PATCH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:8
Rack::PATH_INFO = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:29
Rack::POST = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:30
Rack::PUT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:12
Rack::QUERY_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/query_parser.rb:7
class Rack::QueryParser
  # pkg:gem/rack#lib/rack/query_parser.rb:62
  def initialize(params_class, param_depth_limit, bytesize_limit: T.unsafe(nil), params_limit: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:60
  def bytesize_limit; end

  # pkg:gem/rack#lib/rack/query_parser.rb:196
  def make_params; end

  # pkg:gem/rack#lib/rack/query_parser.rb:200
  def new_depth_limit(param_depth_limit); end

  # normalize_params recursively expands parameters into structural types. If
  # the structural types represented by two different parameter names are in
  # conflict, a ParameterTypeError is raised.  The depth argument is deprecated
  # and should no longer be used, it is kept for backwards compatibility with
  # earlier versions of rack.
  #
  # pkg:gem/rack#lib/rack/query_parser.rb:124
  def normalize_params(params, name, v, _depth = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:40
  def param_depth_limit; end

  # parse_nested_query expands a query string into structural types. Supported
  # types are Arrays, Hashes and basic value types. It is possible to supply
  # query strings with parameters of conflicting types, in this case a
  # ParameterTypeError is raised. Users are encouraged to return a 400 in this
  # case.
  #
  # pkg:gem/rack#lib/rack/query_parser.rb:109
  def parse_nested_query(qs, separator = T.unsafe(nil)); end

  # Stolen from Mongrel, with some small modifications:
  # Parses a query string by breaking it up at the '&'.  You can also use this
  # to parse cookies by changing the characters used in the second parameter
  # (which defaults to '&').
  #
  # pkg:gem/rack#lib/rack/query_parser.rb:73
  def parse_query(qs, separator = T.unsafe(nil), &unescaper); end

  # Parses a query string by breaking it up at the '&', returning all key-value
  # pairs as an array of [key, value] arrays. Unlike parse_query, this preserves
  # all duplicate keys rather than collapsing them.
  #
  # pkg:gem/rack#lib/rack/query_parser.rb:94
  def parse_query_pairs(qs, separator = T.unsafe(nil)); end

  private

  # pkg:gem/rack#lib/rack/query_parser.rb:128
  def _normalize_params(params, name, v, depth); end

  # pkg:gem/rack#lib/rack/query_parser.rb:222
  def each_query_pair(qs, separator, unescaper = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:210
  def params_hash_has_key?(hash, key); end

  # pkg:gem/rack#lib/rack/query_parser.rb:206
  def params_hash_type?(obj); end

  # pkg:gem/rack#lib/rack/query_parser.rb:253
  def unescape(string, encoding = T.unsafe(nil)); end

  class << self
    # pkg:gem/rack#lib/rack/query_parser.rb:36
    def make_default(param_depth_limit, **options); end
  end
end

# pkg:gem/rack#lib/rack/query_parser.rb:54
Rack::QueryParser::BYTESIZE_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/query_parser.rb:9
Rack::QueryParser::COMMON_SEP = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/query_parser.rb:8
Rack::QueryParser::DEFAULT_SEP = T.let(T.unsafe(nil), Regexp)

# InvalidParameterError is the error that is raised when incoming structural
# parameters (parsed by parse_nested_query) contain invalid format or byte
# sequence.
#
# pkg:gem/rack#lib/rack/query_parser.rb:20
class Rack::QueryParser::InvalidParameterError < ::ArgumentError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/query_parser.rb:57
Rack::QueryParser::PARAMS_LIMIT = T.let(T.unsafe(nil), Integer)

# ParameterTypeError is the error that is raised when incoming structural
# parameters (parsed by parse_nested_query) contain conflicting types.
#
# pkg:gem/rack#lib/rack/query_parser.rb:13
class Rack::QueryParser::ParameterTypeError < ::TypeError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/query_parser.rb:257
class Rack::QueryParser::Params < ::Hash
  # pkg:gem/rack#lib/rack/query_parser.rb:258
  def to_params_hash; end
end

# ParamsTooDeepError is the old name for the error that is raised when params
# are recursively nested over the specified limit. Make it the same as
# as QueryLimitError, so that code that rescues ParamsTooDeepError error
# to handle bad query strings also now handles other limits.
#
# pkg:gem/rack#lib/rack/query_parser.rb:34
Rack::QueryParser::ParamsTooDeepError = Rack::QueryParser::QueryLimitError

# QueryLimitError is for errors raised when the query provided exceeds one
# of the query parser limits.
#
# pkg:gem/rack#lib/rack/query_parser.rb:26
class Rack::QueryParser::QueryLimitError < ::RangeError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/constants.rb:43
Rack::RACK_EARLY_HINTS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:44
Rack::RACK_ERRORS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:51
Rack::RACK_HIJACK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:46
Rack::RACK_INPUT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:52
Rack::RACK_IS_HIJACK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:45
Rack::RACK_LOGGER = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:67
Rack::RACK_METHODOVERRIDE_ORIGINAL_METHOD = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:54
Rack::RACK_MULTIPART_BUFFER_SIZE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:55
Rack::RACK_MULTIPART_TEMPFILE_FACTORY = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:57
Rack::RACK_PROTOCOL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:53
Rack::RACK_RECURSIVE_INCLUDE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:63
Rack::RACK_REQUEST_COOKIE_HASH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:64
Rack::RACK_REQUEST_COOKIE_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:62
Rack::RACK_REQUEST_FORM_ERROR = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:59
Rack::RACK_REQUEST_FORM_HASH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:58
Rack::RACK_REQUEST_FORM_INPUT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:60
Rack::RACK_REQUEST_FORM_PAIRS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:61
Rack::RACK_REQUEST_FORM_VARS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:65
Rack::RACK_REQUEST_QUERY_HASH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:66
Rack::RACK_REQUEST_QUERY_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:56
Rack::RACK_RESPONSE_FINISHED = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:47
Rack::RACK_SESSION = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:48
Rack::RACK_SESSION_OPTIONS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:49
Rack::RACK_SHOWSTATUS_DETAIL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:42
Rack::RACK_TEMPFILES = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:50
Rack::RACK_URL_SCHEME = T.let(T.unsafe(nil), String)

# Rack environment variables
#
# pkg:gem/rack#lib/rack/constants.rb:41
Rack::RACK_VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:9
Rack::REQUEST_METHOD = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:10
Rack::REQUEST_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:11
Rack::SCRIPT_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:14
Rack::SERVER_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:15
Rack::SERVER_PORT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:13
Rack::SERVER_PROTOCOL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:24
Rack::SET_COOKIE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:38
Rack::TRACE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:25
Rack::TRANSFER_ENCODING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:37
Rack::UNLINK = T.let(T.unsafe(nil), String)

# Rack::Utils contains a grab-bag of useful methods for writing web
# applications adopted from all kinds of Ruby libraries.
#
# pkg:gem/rack#lib/rack/utils.rb:20
module Rack::Utils
  private

  # Return best accept value to use, based on the algorithm
  # in RFC 2616 Section 14.  If there are multiple best
  # matches (same specificity and quality), the value returned
  # is arbitrary.
  #
  # pkg:gem/rack#lib/rack/utils.rb:227
  def best_q_match(q_value_header, available_mimes); end

  # pkg:gem/rack#lib/rack/utils.rb:120
  def build_nested_query(value, prefix = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:110
  def build_query(params); end

  # Parses the "Range:" header, if present, into an array of Range objects.
  # Returns nil if the header is missing or syntactically invalid.
  # Returns an empty array if none of the ranges are satisfiable.
  #
  # pkg:gem/rack#lib/rack/utils.rb:492
  def byte_ranges(env, size, max_ranges: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:692
  def clean_path_info(path_info); end

  # :nocov:
  #
  # pkg:gem/rack#lib/rack/utils.rb:91
  def clock_time; end

  # pkg:gem/rack#lib/rack/utils.rb:450
  def delete_cookie_header!(headers, key, value = T.unsafe(nil)); end

  # :call-seq:
  #   delete_set_cookie_header(key, value = {}) -> encoded string
  #
  # Generate an encoded string based on the given +key+ and +value+ using
  # set_cookie_header for the purpose of causing the specified cookie to be
  # deleted. The +value+ may be an instance of +Hash+ and can include
  # attributes as outlined by set_cookie_header. The encoded cookie will have
  # a +max_age+ of 0 seconds, an +expires+ date in the past and an empty
  # +value+. When used with the +set-cookie+ header, it will cause the client
  # to *remove* any matching cookie.
  #
  #   delete_set_cookie_header("myname")
  #   # => "myname=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"
  #
  # pkg:gem/rack#lib/rack/utils.rb:446
  def delete_set_cookie_header(key, value = T.unsafe(nil)); end

  # :call-seq:
  #   delete_set_cookie_header!(header, key, value = {}) -> header value
  #
  # Set an expired cookie in the specified headers with the given cookie
  # +key+ and +value+ using delete_set_cookie_header. This causes
  # the client to immediately delete the specified cookie.
  #
  #   delete_set_cookie_header!(nil, "mycookie")
  #   # => "mycookie=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"
  #
  # If the header is non-nil, it will be modified in place.
  #
  #   header = []
  #   delete_set_cookie_header!(header, "mycookie")
  #   # => ["mycookie=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"]
  #   header
  #   # => ["mycookie=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"]
  #
  # pkg:gem/rack#lib/rack/utils.rb:474
  def delete_set_cookie_header!(header, key, value = T.unsafe(nil)); end

  # URI escapes. (CGI style space to +)
  #
  # pkg:gem/rack#lib/rack/utils.rb:40
  def escape(s); end

  # Escape ampersands, brackets and quotes to their HTML/XML entities.
  #
  # pkg:gem/rack#lib/rack/utils.rb:243
  def escape_html(_arg0); end

  # Like URI escaping, but with %20 instead of +. Strictly speaking this is
  # true URI escaping.
  #
  # pkg:gem/rack#lib/rack/utils.rb:46
  def escape_path(s); end

  # pkg:gem/rack#lib/rack/utils.rb:152
  def forwarded_values(forwarded_header); end

  # pkg:gem/rack#lib/rack/utils.rb:496
  def get_byte_ranges(http_range, size, max_ranges: T.unsafe(nil)); end

  # :call-seq:
  #   parse_cookies(env) -> hash
  #
  # Parse cookies from the provided request environment using
  # parse_cookies_header. Returns a map of cookie +key+ to cookie +value+.
  #
  #   parse_cookies({'HTTP_COOKIE' => 'myname=myvalue'})
  #   # => {'myname' => 'myvalue'}
  #
  # pkg:gem/rack#lib/rack/utils.rb:347
  def parse_cookies(env); end

  # :call-seq:
  #   parse_cookies_header(value) -> hash
  #
  # Parse cookies from the provided header +value+ according to RFC6265. The
  # syntax for cookie headers only supports semicolons. Returns a map of
  # cookie +key+ to cookie +value+.
  #
  #   parse_cookies_header('myname=myvalue; max-age=0')
  #   # => {"myname"=>"myvalue", "max-age"=>"0"}
  #
  # pkg:gem/rack#lib/rack/utils.rb:328
  def parse_cookies_header(value); end

  # pkg:gem/rack#lib/rack/utils.rb:106
  def parse_nested_query(qs, d = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:102
  def parse_query(qs, d = T.unsafe(nil), &unescaper); end

  # pkg:gem/rack#lib/rack/utils.rb:138
  def q_values(q_value_header); end

  # pkg:gem/rack#lib/rack/utils.rb:485
  def rfc2822(time); end

  # Constant time string comparison.
  #
  # NOTE: the values compared should be of fixed length, such as strings
  # that have already been processed by HMAC. This should not be used
  # on variable length plaintext strings because it could leak length info
  # via timing attacks.
  #
  # pkg:gem/rack#lib/rack/utils.rb:540
  def secure_compare(a, b); end

  # Given an array of available encoding strings, and an array of
  # acceptable encodings for a request, where each element of the
  # acceptable encodings array is an array where the first element
  # is an encoding name and the second element is the numeric
  # priority for the encoding, return the available encoding with
  # the highest priority.
  #
  # The accept_encoding argument is typically generated by calling
  # Request#accept_encoding.
  #
  # Example:
  #
  #   select_best_encoding(%w(compress gzip identity),
  #                        [["compress", 0.5], ["gzip", 1.0]])
  #   # => "gzip"
  #
  # To reduce denial of service potential, only the first 16
  # acceptable encodings are considered.
  #
  # pkg:gem/rack#lib/rack/utils.rb:274
  def select_best_encoding(available_encodings, accept_encoding); end

  # :call-seq:
  #   set_cookie_header(key, value) -> encoded string
  #
  # Generate an encoded string using the provided +key+ and +value+ suitable
  # for the +set-cookie+ header according to RFC6265. The +value+ may be an
  # instance of either +String+ or +Hash+. If the cookie key is invalid (as
  # defined by RFC6265), an +ArgumentError+ will be raised.
  #
  # If the cookie +value+ is an instance of +Hash+, it considers the following
  # cookie attribute keys: +domain+, +max_age+, +expires+ (must be instance
  # of +Time+), +secure+, +http_only+, +same_site+ and +value+. For more
  # details about the interpretation of these fields, consult
  # [RFC6265 Section 5.2](https://datatracker.ietf.org/doc/html/rfc6265#section-5.2).
  #
  #   set_cookie_header("myname", "myvalue")
  #   # => "myname=myvalue"
  #
  #   set_cookie_header("myname", {value: "myvalue", max_age: 10})
  #   # => "myname=myvalue; max-age=10"
  #
  # pkg:gem/rack#lib/rack/utils.rb:376
  def set_cookie_header(key, value); end

  # :call-seq:
  #   set_cookie_header!(headers, key, value) -> header value
  #
  # Append a cookie in the specified headers with the given cookie +key+ and
  # +value+ using set_cookie_header.
  #
  # If the headers already contains a +set-cookie+ key, it will be converted
  # to an +Array+ if not already, and appended to.
  #
  # pkg:gem/rack#lib/rack/utils.rb:420
  def set_cookie_header!(headers, key, value); end

  # pkg:gem/rack#lib/rack/utils.rb:674
  def status_code(status); end

  # Unescapes a URI escaped string with +encoding+. +encoding+ will be the
  # target encoding of the string returned, and it defaults to UTF-8
  #
  # pkg:gem/rack#lib/rack/utils.rb:58
  def unescape(s, encoding = T.unsafe(nil)); end

  # Unescapes the **path** component of a URI.  See Rack::Utils.unescape for
  # unescaping query parameters or form components.
  #
  # pkg:gem/rack#lib/rack/utils.rb:52
  def unescape_path(s); end

  # pkg:gem/rack#lib/rack/utils.rb:709
  def valid_path?(path); end

  class << self
    # Return best accept value to use, based on the algorithm
    # in RFC 2616 Section 14.  If there are multiple best
    # matches (same specificity and quality), the value returned
    # is arbitrary.
    #
    # pkg:gem/rack#lib/rack/utils.rb:227
    def best_q_match(q_value_header, available_mimes); end

    # pkg:gem/rack#lib/rack/utils.rb:120
    def build_nested_query(value, prefix = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:110
    def build_query(params); end

    # Parses the "Range:" header, if present, into an array of Range objects.
    # Returns nil if the header is missing or syntactically invalid.
    # Returns an empty array if none of the ranges are satisfiable.
    #
    # pkg:gem/rack#lib/rack/utils.rb:492
    def byte_ranges(env, size, max_ranges: T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:692
    def clean_path_info(path_info); end

    # :nocov:
    #
    # pkg:gem/rack#lib/rack/utils.rb:91
    def clock_time; end

    # pkg:gem/rack#lib/rack/utils.rb:30
    def default_query_parser; end

    # pkg:gem/rack#lib/rack/utils.rb:30
    def default_query_parser=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:450
    def delete_cookie_header!(headers, key, value = T.unsafe(nil)); end

    # :call-seq:
    #   delete_set_cookie_header(key, value = {}) -> encoded string
    #
    # Generate an encoded string based on the given +key+ and +value+ using
    # set_cookie_header for the purpose of causing the specified cookie to be
    # deleted. The +value+ may be an instance of +Hash+ and can include
    # attributes as outlined by set_cookie_header. The encoded cookie will have
    # a +max_age+ of 0 seconds, an +expires+ date in the past and an empty
    # +value+. When used with the +set-cookie+ header, it will cause the client
    # to *remove* any matching cookie.
    #
    #   delete_set_cookie_header("myname")
    #   # => "myname=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"
    #
    # pkg:gem/rack#lib/rack/utils.rb:446
    def delete_set_cookie_header(key, value = T.unsafe(nil)); end

    # :call-seq:
    #   delete_set_cookie_header!(header, key, value = {}) -> header value
    #
    # Set an expired cookie in the specified headers with the given cookie
    # +key+ and +value+ using delete_set_cookie_header. This causes
    # the client to immediately delete the specified cookie.
    #
    #   delete_set_cookie_header!(nil, "mycookie")
    #   # => "mycookie=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"
    #
    # If the header is non-nil, it will be modified in place.
    #
    #   header = []
    #   delete_set_cookie_header!(header, "mycookie")
    #   # => ["mycookie=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"]
    #   header
    #   # => ["mycookie=; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 GMT"]
    #
    # pkg:gem/rack#lib/rack/utils.rb:474
    def delete_set_cookie_header!(header, key, value = T.unsafe(nil)); end

    # URI escapes. (CGI style space to +)
    #
    # pkg:gem/rack#lib/rack/utils.rb:40
    def escape(s); end

    # Escape ampersands, brackets and quotes to their HTML/XML entities.
    #
    # pkg:gem/rack#lib/rack/utils.rb:243
    def escape_html(_arg0); end

    # Like URI escaping, but with %20 instead of +. Strictly speaking this is
    # true URI escaping.
    #
    # pkg:gem/rack#lib/rack/utils.rb:46
    def escape_path(s); end

    # pkg:gem/rack#lib/rack/utils.rb:152
    def forwarded_values(forwarded_header); end

    # pkg:gem/rack#lib/rack/utils.rb:496
    def get_byte_ranges(http_range, size, max_ranges: T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:65
    def multipart_file_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:65
    def multipart_file_limit=(_arg0); end

    # multipart_part_limit is the original name of multipart_file_limit, but
    # the limit only counts parts with filenames.
    #
    # pkg:gem/rack#lib/rack/utils.rb:69
    def multipart_part_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:70
    def multipart_part_limit=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:63
    def multipart_total_part_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:63
    def multipart_total_part_limit=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:82
    def param_depth_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:86
    def param_depth_limit=(v); end

    # :call-seq:
    #   parse_cookies(env) -> hash
    #
    # Parse cookies from the provided request environment using
    # parse_cookies_header. Returns a map of cookie +key+ to cookie +value+.
    #
    #   parse_cookies({'HTTP_COOKIE' => 'myname=myvalue'})
    #   # => {'myname' => 'myvalue'}
    #
    # pkg:gem/rack#lib/rack/utils.rb:347
    def parse_cookies(env); end

    # :call-seq:
    #   parse_cookies_header(value) -> hash
    #
    # Parse cookies from the provided header +value+ according to RFC6265. The
    # syntax for cookie headers only supports semicolons. Returns a map of
    # cookie +key+ to cookie +value+.
    #
    #   parse_cookies_header('myname=myvalue; max-age=0')
    #   # => {"myname"=>"myvalue", "max-age"=>"0"}
    #
    # pkg:gem/rack#lib/rack/utils.rb:328
    def parse_cookies_header(value); end

    # pkg:gem/rack#lib/rack/utils.rb:106
    def parse_nested_query(qs, d = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:102
    def parse_query(qs, d = T.unsafe(nil), &unescaper); end

    # pkg:gem/rack#lib/rack/utils.rb:138
    def q_values(q_value_header); end

    # pkg:gem/rack#lib/rack/utils.rb:485
    def rfc2822(time); end

    # Constant time string comparison.
    #
    # NOTE: the values compared should be of fixed length, such as strings
    # that have already been processed by HMAC. This should not be used
    # on variable length plaintext strings because it could leak length info
    # via timing attacks.
    #
    # pkg:gem/rack#lib/rack/utils.rb:540
    def secure_compare(a, b); end

    # Given an array of available encoding strings, and an array of
    # acceptable encodings for a request, where each element of the
    # acceptable encodings array is an array where the first element
    # is an encoding name and the second element is the numeric
    # priority for the encoding, return the available encoding with
    # the highest priority.
    #
    # The accept_encoding argument is typically generated by calling
    # Request#accept_encoding.
    #
    # Example:
    #
    #   select_best_encoding(%w(compress gzip identity),
    #                        [["compress", 0.5], ["gzip", 1.0]])
    #   # => "gzip"
    #
    # To reduce denial of service potential, only the first 16
    # acceptable encodings are considered.
    #
    # pkg:gem/rack#lib/rack/utils.rb:274
    def select_best_encoding(available_encodings, accept_encoding); end

    # :call-seq:
    #   set_cookie_header(key, value) -> encoded string
    #
    # Generate an encoded string using the provided +key+ and +value+ suitable
    # for the +set-cookie+ header according to RFC6265. The +value+ may be an
    # instance of either +String+ or +Hash+. If the cookie key is invalid (as
    # defined by RFC6265), an +ArgumentError+ will be raised.
    #
    # If the cookie +value+ is an instance of +Hash+, it considers the following
    # cookie attribute keys: +domain+, +max_age+, +expires+ (must be instance
    # of +Time+), +secure+, +http_only+, +same_site+ and +value+. For more
    # details about the interpretation of these fields, consult
    # [RFC6265 Section 5.2](https://datatracker.ietf.org/doc/html/rfc6265#section-5.2).
    #
    #   set_cookie_header("myname", "myvalue")
    #   # => "myname=myvalue"
    #
    #   set_cookie_header("myname", {value: "myvalue", max_age: 10})
    #   # => "myname=myvalue; max-age=10"
    #
    # pkg:gem/rack#lib/rack/utils.rb:376
    def set_cookie_header(key, value); end

    # :call-seq:
    #   set_cookie_header!(headers, key, value) -> header value
    #
    # Append a cookie in the specified headers with the given cookie +key+ and
    # +value+ using set_cookie_header.
    #
    # If the headers already contains a +set-cookie+ key, it will be converted
    # to an +Array+ if not already, and appended to.
    #
    # pkg:gem/rack#lib/rack/utils.rb:420
    def set_cookie_header!(headers, key, value); end

    # pkg:gem/rack#lib/rack/utils.rb:674
    def status_code(status); end

    # Unescapes a URI escaped string with +encoding+. +encoding+ will be the
    # target encoding of the string returned, and it defaults to UTF-8
    #
    # pkg:gem/rack#lib/rack/utils.rb:58
    def unescape(s, encoding = T.unsafe(nil)); end

    # Unescapes the **path** component of a URI.  See Rack::Utils.unescape for
    # unescaping query parameters or form components.
    #
    # pkg:gem/rack#lib/rack/utils.rb:52
    def unescape_path(s); end

    # pkg:gem/rack#lib/rack/utils.rb:709
    def valid_path?(path); end
  end
end

# pkg:gem/rack#lib/rack/utils.rb:149
Rack::Utils::ALLOWED_FORWARDED_PARAMS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:25
Rack::Utils::COMMON_SEP = T.let(T.unsafe(nil), Hash)

# Context allows the use of a compatible middleware at different points
# in a request handling stack. A compatible middleware must define
# #context which should take the arguments env and app. The first of which
# would be the request environment. The second of which would be the rack
# application that the request would be forwarded to.
#
# pkg:gem/rack#lib/rack/utils.rb:563
class Rack::Utils::Context
  # pkg:gem/rack#lib/rack/utils.rb:566
  def initialize(app_f, app_r); end

  # pkg:gem/rack#lib/rack/utils.rb:564
  def app; end

  # pkg:gem/rack#lib/rack/utils.rb:571
  def call(env); end

  # pkg:gem/rack#lib/rack/utils.rb:579
  def context(env, app = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:564
  def for; end

  # pkg:gem/rack#lib/rack/utils.rb:575
  def recontext(app); end
end

# pkg:gem/rack#lib/rack/utils.rb:24
Rack::Utils::DEFAULT_SEP = T.let(T.unsafe(nil), Regexp)

# Every standard HTTP code mapped to the appropriate message.
# Generated with:
#   curl -s https://www.iana.org/assignments/http-status-codes/http-status-codes-1.csv \
#     | ruby -rcsv -e "puts CSV.parse(STDIN, headers: true) \
#     .reject {|v| v['Description'] == 'Unassigned' or v['Description'].include? '(' } \
#     .map {|v| %Q/#{v['Value']} => '#{v['Description']}'/ }.join(','+?\n)"
#
# pkg:gem/rack#lib/rack/utils.rb:590
Rack::Utils::HTTP_STATUS_CODES = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:22
Rack::Utils::InvalidParameterError = Rack::QueryParser::InvalidParameterError

# pkg:gem/rack#lib/rack/utils.rb:26
Rack::Utils::KeySpaceConstrainedParams = Rack::QueryParser::Params

# pkg:gem/rack#lib/rack/utils.rb:707
Rack::Utils::NULL_BYTE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/utils.rb:660
Rack::Utils::OBSOLETE_SYMBOLS_TO_STATUS_CODES = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:668
Rack::Utils::OBSOLETE_SYMBOL_MAPPINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:690
Rack::Utils::PATH_SEPS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/utils.rb:21
Rack::Utils::ParameterTypeError = Rack::QueryParser::ParameterTypeError

# pkg:gem/rack#lib/rack/utils.rb:23
Rack::Utils::ParamsTooDeepError = Rack::QueryParser::QueryLimitError

# Responses with HTTP status codes that should not have an entity body
#
# pkg:gem/rack#lib/rack/utils.rb:654
Rack::Utils::STATUS_WITH_NO_ENTITY_BODY = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:656
Rack::Utils::SYMBOL_TO_STATUS_CODE = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:27
Rack::Utils::URI_PARSER = T.let(T.unsafe(nil), URI::RFC2396_Parser)

# A valid cookie key according to RFC6265 and RFC2616.
# A <cookie-name> can be any US-ASCII characters, except control characters, spaces, or tabs. It also must not contain a separator character like the following: ( ) < > @ , ; : \ " / [ ] ? = { }.
#
# pkg:gem/rack#lib/rack/utils.rb:353
Rack::Utils::VALID_COOKIE_KEY = T.let(T.unsafe(nil), Regexp)
