repos:
-   repo: local
    hooks:
    -   id: rubocop
        name: Rubocop
        language: system
        files: \.(rb)$
        entry: bundle exec rubocop
        args:
          - --server
          - --auto-correct
          - --color
