repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruboclean
        name: Ruboclean
        language: system
        files: .rubocop.yml
        entry: bundle exec ruboclean
        args:
          - --silent
          - --preserve-comments
          - --preserve-paths

      - id: rubocop
        name: Rubocop
        language: system
        types: [ruby]
        entry: bundle exec rubocop
        require_serial: true
        args:
          - --server
          - --autocorrect
          - --color

      - id: biome
        name: Biome
        language: system
        types_or: [javascript, jsx, ts, tsx, json]
        entry: node_modules/.bin/biome check --write

      - id: prettier-yaml
        name: Prettier YAML
        language: system
        types: [yaml]
        entry: node_modules/.bin/prettier
        args:
          - --parser=yaml
          - --write
          - --cache
          - --cache-strategy=content
        require_serial: true # for proper cache behavior
        exclude: (?x)(
          ^\.rubocop.*\.yml)$

      - id: sorbet
        name: Sorbet
        language: system
        types: [ruby]
        files: \.(rb)$
        entry: bundle exec srb tc
        pass_filenames: false

      - id: actionlint
        name: Lint Github workflows
        types: [yaml]
        language: docker_image
        entry: rhysd/actionlint:1.7.7
        files: ^\.github/workflows/

      - id: hadolint
        name: Lint Dockerfiles
        language: docker_image
        entry: hadolint/hadolint hadolint
        types: [dockerfile]
