repos:
-   repo: local
    hooks:
    -   id: rubocop
        name: Rubocop
        language: system
        files: \.(rb)$
        entry: bundle exec rubocop
        require_serial: true
        args:
          - --server
          - --autocorrect
          - --color
