require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120
  Exclude:
    - "**/test/*.rb"

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/HashLikeCase:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PerlBackrefs:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 1

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 1
