# typed: strict
# frozen_string_literal: true

require 'sorbet-runtime'
require 'minitest/autorun'
require_relative('../lib/07_laboratories')

class LaboratoriesTest < Minitest::Test
  extend T::Sig
  sig { returns(T.class_of(Laboratories)) }
  def described_class = Laboratories

  sig { returns(String) }
  def input = <<~INPUT
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
  INPUT

  sig { void }
  def test_part1
    assert_equal 21, described_class.new(input).part1
  end

  sig { void }
  def test_part2
    assert_equal 40, described_class.new(input).part2
  end
end
