name: Ruby

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test

      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
