name: Ruby

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Install node dependencies
        run: yarn install

      - name: troubleshoot
        run: |
          ls -la
          ls -la node_modules

      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: bundle exec rake test
